# Generated by Django 2.1.1 on 2018-10-29 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token_payment', models.CharField(max_length=50, unique=True)),
                ('token_isValid', models.BooleanField(default=True)),
                ('payment_status', models.IntegerField(choices=[(1, 'Awaiting Payment'), (2, 'Payment Error'), (3, 'Order Cancelled'), (4, 'Payment Completed')], default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_payment', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_id', models.IntegerField()),
                ('season_num', models.IntegerField(blank=True, null=True)),
                ('purchase_id', models.ManyToManyField(to='stroam.Purchase')),
            ],
        ),
    ]
